[package]
name = "pts_compiler"
version = "0.1.0"
edition = "2021"

[lib]
name = "pts_compiler"
paths = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
